name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'ScilifelabDataCentre/dynamic-cron'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: scilifelabdatacentre/dynamic-cron
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: "latest"
